use shipping;

CREATE TABLE `Ports` (
HomePort VARCHAR(40) NOT NULL,
City VARCHAR(40) NOT NULL,
Country VARCHAR(40) NOT NULL,
PRIMARY KEY(HomePort));

CREATE TABLE `Ships` (
ShipName VARCHAR(20) UNIQUE NOT NULL PRIMARY KEY,
DisplacementTons DOUBLE NOT NULL,
CaptainName VARCHAR(40) NOT NULL,
NumOfCrew INT NOT NULL,
HomePort VARCHAR(40) NOT NULL,
YearBuilt YEAR(4) NOT NULL,
FOREIGN KEY(HomePort) REFERENCES Ports(HomePort));

CREATE TABLE `Containers`(
ContainerID INT NOT NULL PRIMARY KEY,
HeightFT INT NOT NULL,
WidthFT INT NOT NULL,
LengthFT INT NOT NULL,
WeightLBS DOUBLE NOT NULL,
ShipName VARCHAR(20),
FOREIGN KEY(ShipName) REFERENCES Ships(ShipName));


